language: node_js

node_js:
    - "8"

sudo: false

git:
    submodules: false

cache:
    directories:
        - node_modules

#before_script:
    # Prepare for automated tests
    #- npm install

script:
    # Run tests
    - cd react-frontend && npm install && npm run build
    - npm test
