language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

cache:
    directories:
        - node_modules

before_script:
    # Prepare for automated tests
    - npm install

script:
    # Run tests
    - npm run build
    - npm test
