language: node_js
node_js:
  - "iojs"
  - "7"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:
    # Prepare for automated tests
    - make install



script:
    # Run tests
    - make test
