language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

before_script:
    # Prepare for automated tests
    - npm install

script:
    # Run tests
    - make test
