version: "2"
services:
  node7:
    image: "node:7"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DBWEBB_PORT=1337
    volumes:
      - ./:/home/node/app
    ports:
      - "1337:1337"
    command: "npm start"
  node8:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DBWEBB_PORT=1338
    volumes:
      - ./:/home/node/app
    ports:
      - "1338:1338"
    command: "npm start"
  node9:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DBWEBB_PORT=1339
    volumes:
      - ./:/home/node/app
    ports:
      - "1339:1339"
    command: "npm start"
